language: ruby
cache: bundler
sudo: false

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5

gemfile:
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails6.0.gemfile

matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/rails6.0.gemfile

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
