language: ruby
cache: bundler
sudo: false

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0


gemfile:
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
